"""Create tables owners, pets

Revision ID: 5605a076f5eb
Revises: 
Create Date: 2024-01-12 14:03:18.720681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5605a076f5eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
